[package]
name = "quest_nft_contract"
version = "0.1.0"
authors = ["th0rgal <thomas@starknet.id>"]
description = "Contract of the starknet quest nft contract"
repository = "https://github.com/starknet-id/quest_nft_contract"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.3.0-rc0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true

[lib]
sierra = true
casm = false
